name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_COLOR: 2

permissions:
  contents: read

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [24]
        include:
          - os: macos-latest
            node: 24
          - os: windows-latest
            node: 24

    steps:
      - name: Clone repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install pnpm and Node.js
        uses: pnpm/setup@c9883cc79df532ad1a7b81bf9ab944ceb090d65c # v2.0.0
        with:
          runtime: node@${{ matrix.node }}
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: npm test
