name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_COLOR: 2

permissions:
  contents: read

jobs:
  test:
    name: Node 24 on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install pnpm and Node.js
        uses: pnpm/setup@c9883cc79df532ad1a7b81bf9ab944ceb090d65c # v2.0.0
        with:
          runtime: node@24
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Run Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: coverage/lcov.info
          github-token: "${{ secrets.GITHUB_TOKEN }}"
